before_install:
  - gem update --system
  - gem --version
bundler_args: --without development
rvm:
  - jruby-1.6.7
env:
  - IDENTITY_MAP="true" JRUBY_OPTS="--1.8"
  - IDENTITY_MAP="false" JRUBY_OPTS="--1.8"
  - IDENTITY_MAP="true" JRUBY_OPTS="--1.9"
  - IDENTITY_MAP="false" JRUBY_OPTS="--1.9"
